export const phoneticModes = {
    standard: {
        A: "Alpha",
        B: "Bravo",
        C: "Charlie",
        D: "Delta",
        E: "Echo",
        F: "Foxtrot",
        G: "Golf",
        H: "Hotel",
        I: "India",
        J: "Juliett",
        K: "Kilo",
        L: "Lima",
        M: "Mike",
        N: "November",
        O: "Oscar",
        P: "Papa",
        Q: "Quebec",
        R: "Romeo",
        S: "Sierra",
        T: "Tango",
        U: "Uniform",
        V: "Victor",
        W: "Whiskey",
        X: "X-ray",
        Y: "Yankee",
        Z: "Zulu",
        " ": "(space)"
    },
    cursed: {
        A: "Aisle",
        B: "Bdellium",
        C: "Cue",
        D: "Djinn",
        E: "Ewe",
        F: "Fjall",
        G: "Gnome",
        H: "Heir",
        I: "Iceland",
        J: "Jalapeño",
        K: "Knot",
        L: "Llandudno",
        M: "Mnemonic",
        N: "Ndebele",
        O: "Ouija",
        P: "Pterodactyl",
        Q: "Qatar",
        R: "Rwanda",
        S: "Sea",
        T: "Tsar",
        U: "Urn",
        V: "Voila",
        W: "Why",
        X: "Xenon",
        Y: "Yttrium",
        Z: "Zhuzh",
        " ": "(silence)",
        "'": "(whisper)",
        ".": "(glitch)",
        ",": "(shiver)",
        "-": "(void)",
        "!": "(scream)",
        "?": "(confusion)",
        "_": "(undefined)",
        "@": "(at)"
    },
    hipster: {
        A: "Açai",
        B: "Burrata",
        C: "Chia",
        D: "Dukkah",
        E: "Einkorn",
        F: "Focaccia",
        G: "Gochujang",
        H: "Hemp",
        I: "Icebrew",
        J: "Jackfruit",
        K: "Kombucha",
        L: "Labneh",
        M: "Matcha",
        N: "Nduja",
        O: "Oatmilk",
        P: "Poke",
        Q: "Quinoa",
        R: "Rooibos",
        S: "Sourdough",
        T: "Turmeric",
        U: "Ube",
        V: "Verjus",
        W: "Wakame",
        X: "Xanthan",
        Y: "Yuzu",
        Z: "Za’atar",
        " ": "(space)",
        "'": "(ownership)",
        ".": "(finish)",
        ",": "(breath)",
        "-": "(connection)",
        "!": "(emphasis)",
        "?": "(curiosity)",
        "@": "(at)"
    },
    business: {
        A: "Actionable",
        B: "Blue-sky",
        C: "Circle-back",
        D: "Deep-dive",
        E: "Ecosystem",
        F: "Funnel",
        G: "Go-forward",
        H: "Hackathon",
        I: "Ideation",
        J: "Journey",
        K: "KPI",
        L: "Leverage",
        M: "Mindshare",
        N: "Net-new",
        O: "Optics",
        P: "Paradigm",
        Q: "Quick-win",
        R: "Roadmap",
        S: "Synergy",
        T: "Touch-base",
        U: "Utilisation",
        V: "Value-add",
        W: "Workflow",
        X: "X-functional",
        Y: "Year-over-year",
        Z: "Zero-sum",
        " ": "(space)",
        "'": "(apostrophe)",
        ".": "(stop)",
        ",": "(comma)",
        "-": "(pipeline)",
        "!": "(impact)",
        "?": "(clarity)",
        "_": "(underscore)",
        "@": "(at)"
    },
    insta: {
        A: "Authentic-self",
        B: "Boho",
        C: "Curated",
        D: "Detox",
        E: "Engagement",
        F: "Filtered",
        G: "Glow-up",
        H: "Hot-girl-walk",
        I: "Influencer",
        J: "Juice-cleanse",
        K: "Kombucha",
        L: "Lifestyle",
        M: "Manifest",
        N: "Namaste",
        O: "Outfit-of-the-day",
        P: "Partnership",
        Q: "Quiet-luxury",
        R: "Rebrand",
        S: "Self-care",
        T: "Thirst-trap",
        U: "Unboxing",
        V: "Vibes",
        W: "Wanderlust",
        X: "XOXO-bestie",
        Y: "Yoga",
        Z: "Zodiac",
        " ": "(gap)",
        "'": "(sparkle)",
        ".": "(full stop vibes)",
        ",": "(pause)",
        "-": "(soft dash)",
        "!": "(excited energy)",
        "?": "(confused queen moment)",
        "_": "(deadass serious)",
        "@": "(handle)"
    },
    techbro: {
        A: "AI-first",
        B: "Blockchain",
        C: "Crypto",
        D: "Disrupt",
        E: "Exit",
        F: "Founder-mode",
        G: "Growth-hack",
        H: "Hyper-scale",
        I: "Iteration",
        J: "Jetpack",
        K: "Kubernetes",
        L: "Lean",
        M: "Monetise",
        N: "Network-effect",
        O: "Optimise",
        P: "Pivot",
        Q: "Quantum",
        R: "Runway",
        S: "Stealth",
        T: "Tokenise",
        U: "Unicorn",
        V: "VC-backed",
        W: "Web3",
        X: "XaaS",
        Y: "YoY-growth",
        Z: "Zero-to-one",
        " ": "(space)",
        "'": "(quote)",
        ".": "(dot)",
        ",": "(comma)",
        "-": "(dash)",
        "!": "(bang)",
        "?": "(query)",
        "_": "(underscore)",
        "@": "(at)"
    }
};

export const prosodyProfiles = {
    standard: {
        word: { rate: 1, pitch: 1, pre: 0, post: 120 },
        bracket: { rate: 0.95, pitch: 1.1, pre: 200, post: 150 },
        raw: { rate: 1, pitch: 1, pre: 0, post: 60 },
        bracketStrategy: "flat"
    },

    cursed: {
        word: { rate: 0.85, pitch: 0.7, pre: 0, post: 140 },
        bracket: { rate: 0.8, pitch: 0.9, pre: 400, post: 200 },
        raw: { rate: 0.9, pitch: 0.8, pre: 0, post: 80 },
        bracketStrategy: "chunked"
    },

    hipster: {
        word: { rate: 0.95, pitch: 1.1, pre: 0, post: 120 },
        bracket: { rate: 1.0, pitch: 1.25, pre: 150, post: 120 },
        raw: { rate: 1, pitch: 1, pre: 0, post: 80 },
        bracketStrategy: "flat"
    },

    business: {
        word: { rate: 1.05, pitch: 0.95, pre: 0, post: 100 },
        bracket: { rate: 1.0, pitch: 1.0, pre: 120, post: 100 },
        raw: { rate: 1.05, pitch: 0.95, pre: 0, post: 60 },
        bracketStrategy: "flat"
    },

    insta: {
        word: { rate: 1.2, pitch: 1.25, pre: 0, post: 100 },

        // key part: uncertainty baseline
        bracket: { rate: 1.05, pitch: 1.2, pre: 80, post: 160 },

        raw: { rate: 1.15, pitch: 1.1, pre: 0, post: 60 },

        bracketStrategy: "rising"
    },

    techbro: {
        word: { rate: 1.1, pitch: 0.9, pre: 0, post: 80 },
        bracket: { rate: 1.05, pitch: 1.0, pre: 100, post: 120 },
        raw: { rate: 1.1, pitch: 0.95, pre: 0, post: 60 },
        bracketStrategy: "flat"
    }
};